# Generated by Django 5.0.1 on 2024-03-02 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentTrailAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='package',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resume', models.FileField(upload_to='resumes')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TalentTrailAPI.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
