# Generated by Django 5.0.1 on 2024-03-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentTrailAPI', '0002_alter_job_experience_alter_job_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='does_profile_match',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='predicted_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
