# Generated by Django 5.0.1 on 2024-06-05 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TalentTrailAPI', '0003_jobapplication_does_profile_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
